### ISSUE TITLE
Проблема с rest сервисом

### ISSUE THREAD

**Issue by grevinden** [korotovskih/v8iservice#1]
есть проблема, никак не работает через rest, даже id клиента не обновляется, не пойму в чем дело, может у вас есть версия ?

вот лог обращений загрузчика:
```
INFO:     127.0.0.1:60344 - "HEAD /WebCommonInfoBases HTTP/1.1" 200 OK
INFO:     127.0.0.1:60346 - "GET /WebCommonInfoBases/CheckInfoBases/?ClientID=00000000-0000-0000-0000-000000000000&InfoBasesCheckCode=00000000-0000-0000-0000-000000000000 HTTP/1.1" 200 OK
INFO:     127.0.0.1:60346 - "GET /WebCommonInfoBases/GetInfoBases/?ClientID=00000000-0000-0000-0000-000000000000&InfoBasesCheckCode=00000000-0000-0000-0000-000000000000 HTTP/1.1" 200 OK
```

версия загрузчика:
![image](https://user-images.githubusercontent.com/1051804/181383784-f652533b-876d-4745-99a1-0a123f56c6b0.png)

в ответ на запрос `GetInfoBases` я выдаю
```
 content-length: 276 
 content-type: application/json 
```
```json
{
  "ClientID ": "d9a534af-86d4-4284-8de9-9a7cd25b8813",
  "InfoBasesCheckCode": "b755c928-3f16-48b4-8f06-826acd8a78eb",
  "InfoBases": "\n[SBS]\nConnect=Srvr=\"10.12.1.16:1641\";Ref=\"bss\";\nFolder=/\nClientConnectionSpeed=Normal\nApp=ThickClient\nWA=1\nVersion=8.3\nAppArch=x86_prt\n"
}
```

**Comment by korotovskih** [comment]
Привет @Albus, а rest контроллеры не работают :shit:

Из тех. журнала видно, что 1cestart умеет в rest, но воспроизвести необходимый интерфейс у меня не получилось, документация на него отсутствует.

Писал год назад в @platform_suggestions пожелание дополнить доку требованиями к реализации rest сервиса инф. баз, но пока ничего :angry:

Таким образом без вариантов, только soap контроллер, запилено на коленочке, но работает :thinking:

**Comment by grevinden** [comment]
https://gist.github.com/Albus/b5ef4e2fbdfb4340294a603746114614

вот так работает, делюсь рецептом -> @korotovskih 
была банальная ошибка, лишний пробел в тексте :)

**Comment by korotovskih** [comment]
@Albus Спасибки! :1st_place_medal:
